#   A basic travis.yml boilerplate for Django projects
#   https://gist.github.com/ndarville/3625246

language: python

python:
  - 3.5

cache: pip

services:
  - mysql
  - postgresql

git:
  depth: 3

env:
  - DJANGO_SETTINGS_MODULE=mtsgo.settings
  - DJANGO_SETTINGS_MODULE=mtsgo.testing.mysql_settings
  - DJANGO_SETTINGS_MODULE=mtsgo.testing.postgres_settings

install:
  - pip install -r requirements.txt --quiet
  - pip install coverage --quiet
  - pip install codecov --quiet

before_script:
  - mysql -e 'CREATE DATABASE mtsgo_test;'
  - psql -c 'create database mtsgo_test;' -U postgres
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py check
  - coverage run --source='.' --omit='manage.py' manage.py test

after_script:
  - codecov --token=b5e3bd2d-2bde-475a-8693-86d45f30b6b8
